# Generated by Django 5.0.1 on 2024-03-22 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0005_alter_booking_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotelbooking.client'),
        ),
    ]
